apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels: 
        app: kafka
    spec:
      containers:
      - name: kafka
        image: binami/kafka
        ports:
        - containerPort: 9092
         env:
        - name: KAFKA_ADVERTISED_PORT
          value: 9092
        - name: KAFKA_ADVERTISED_HOST_NAME
          valueFrom:
            configMapKeyRef:
              name: caching-service-app-config
              key: kafka_url
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: caching-service-app-config
              key: zookeeper_url
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: admintome-test:1:1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
    id: "0"
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092